### ISSUE TITLE
Free Segment lines and special-tool completion broken: getToolCategory is not imported

### ISSUE THREAD

**Issue by wand125** [logicpuzzle-app/puzzle-kit#40]
`src/hooks/useCanvasInteraction.ts` calls `getToolCategory(tool)` in `executeToolUp`, but the symbol is never imported. It is exported from `./interactionStateMachine` (re-export of `../utils/toolCategory`), and the import block at the top of the file omits it.

```ts
const executeToolUp = useCallback((tool, point, isRightClick, isShiftKey) => {
  const category = getToolCategory(tool);   // <- ReferenceError
  ...
  toolUpHandlers[category]?.();
}, [...]);
```

`executeToolUp` therefore throws on **every** mouse up, and nothing after that first line runs. The handlers that only complete on mouse up never fire:

- `special-thermo`, `special-arrow`, `special-cage`, `special-boxline` completion
- straight / free-segment line termination

## Repro

Problem > Line > Center > Free Segment, then drag across the board.

| branch | result | console |
| --- | --- | --- |
| `develop` | line is drawn (2 elements) | clean |
| `puzzle-kit-refactor` | **no line is drawn** | `getToolCategory is not defined` |

Tools that do their work in the move handlers (surface fill, orthogonal lines, exclude) still behave correctly, which is why this is easy to miss.

## Cause

Introduced by 3377b62 `input: refactor canvas interaction and number entry` (2025-12-29). `tsc` already reports it:

```
src/hooks/useCanvasInteraction.ts(234,22): error TS2304: Cannot find name 'getToolCategory'.
```

Present on both `puzzle-kit-refactor` @ 689c49d and the pushed head e0675dc. `develop` is unaffected.

## Fix

Add `getToolCategory` to the existing `./interactionStateMachine` import. Verified with Playwright: the Free Segment line is drawn again and the console is clean.
